export const PREMIUM_FEATRES ={
    AI_UNLIMITED: "AI_UNLIMITED",
    MANTRA_AUDIO: "MANTRA_AUDIO",
    SONGS_FULL: "SONGS_FULL",
    SILENCE_GUIDED: "SILENCE_GUIDED",
    JYOTIRLINGA_DEEP: "JYOTIRLINGA_DEEP",
    KNOWLEDGE_DEEP: "KNOWLEDGE_DEEP",
};